version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www
        depends_on:
            - mongo
        working_dir: /var/www
        command: php artisan serve --host=0.0.0.0 --port=8000

    mongo:
        image: mongo:6
        container_name: mongodb
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data:
